export const initialUsers = [
  {
    id: "user_supercoach",
    email: "gerard.krippeler@souveniirs.com",
    name: "Gérard Krippeler",
    role: "supercoach",
    status: "active",
    password: "password123",
    password_changed: true,
    first_login: false,
    created_at: "2023-01-01T10:00:00.000Z",
    expires_at: null,
    progress: [],
    chapters: [],
    payment_status: 'n/a',
    amount_paid: 0,
  },
  {
    id: "user_coach_1",
    email: "coach@souveniirs.com",
    name: "Coach Souveniirs",
    role: "coach",
    status: "active",
    password: "password123",
    password_changed: true,
    first_login: false,
    created_at: "2023-01-02T10:00:00.000Z",
    expires_at: null,
    progress: [],
    chapters: [],
    payment_status: 'n/a',
    amount_paid: 0,
  },
  {
    id: "user_student_1",
    email: "eleve1@souveniirs.com",
    name: "Alice Martin",
    role: "student",
    status: "active",
    password: "password123",
    password_changed: true,
    temp_password: "TEMP_PASSWORD_1",
    first_login: false,
    created_at: "2023-08-15T10:00:00.000Z",
    expires_at: "2025-10-10T23:59:59.000Z",
    access_duration: 12,
    payment_status: 'paid',
    amount_paid: 899,
    progress: [
      { lessonId: "lec_1", completed: true },
      { lessonId: "lec_2", completed: true },
      { lessonId: "lec_3", completed: false },
    ],
    chapters: [{ chapterId: "chap_1", status: "in_progress", content: "Mon premier chapitre...", updatedAt: "2023-09-08T14:00:00.000Z" }],
  },
  {
    id: "user_student_2",
    email: "eleve2@souveniirs.com",
    name: "Bernard Dubois",
    role: "student",
    status: "active",
    password: "password123",
    temp_password: "AB12CD34",
    password_changed: false,
    first_login: true,
    created_at: "2023-09-01T10:00:00.000Z",
    expires_at: "2025-09-15T23:59:59.000Z",
    access_duration: 6,
    payment_status: 'paid',
    amount_paid: 499,
    progress: [],
    chapters: [],
  },
  {
    id: "user_student_expired",
    email: "expired@souveniirs.com",
    name: "Claire Expirée",
    role: "student",
    status: "expired",
    password: "password123",
    password_changed: true,
    first_login: false,
    created_at: "2022-01-01T10:00:00.000Z",
    expires_at: "2023-01-01T23:59:59.000Z",
    access_duration: 3,
    payment_status: 'paid',
    amount_paid: 299,
    progress: [{ lessonId: "lec_1", completed: true }],
    chapters: [],
  }
];

export const initialModules = [
  {
    id: "mod_1",
    title: "Introduction à l'autobiographie",
    is_active: true,
    lessons: [
      { id: "lec_1", title: "Pourquoi écrire votre histoire ?", duration: 15, content: "Contenu de la leçon 1..." },
      { id: "lec_2", title: "Trouver votre voix unique", duration: 20, content: "Contenu de la leçon 2..." },
      { id: "lec_3", title: "Définir le fil rouge de votre récit", duration: 18, content: "Contenu de la leçon 3..." },
    ],
    chapters: [
      { id: "chap_1", title: "Vos origines", description: "Parlez de votre famille, de votre lieu de naissance..." },
      { id: "chap_2", title: "L'enfance", description: "Les souvenirs marquants, les jeux, l'école..." },
    ],
  },
  {
    id: "mod_2",
    title: "Les grands tournants de votre vie",
    is_active: true,
    lessons: [
      { id: "lec_4", title: "L'adolescence et ses défis", duration: 25, content: "Contenu de la leçon 4..." },
      { id: "lec_5", title: "La vie d'adulte : carrière et famille", duration: 30, content: "Contenu de la leçon 5..." },
    ],
    chapters: [
      { id: "chap_3", title: "Les amitiés qui ont compté", description: "Décrivez les personnes qui ont marqué votre parcours." },
    ],
  },
  {
    id: "mod_3",
    title: "Techniques de narration avancées",
    is_active: false,
    lessons: [],
    chapters: [],
  }
];